namespace:
  name: prowler
serviceAccount:
  name: prowler
cronjob:
  name: prowler
  schedule: "0 0 * * *" #Daily at midnight
  hostPID: true
image:
  repository: toniblyx/prowler
  tag: stable
  pullPolicy: Always
clusterRole:
  name: prowler-read-cluster
clusterRoleBinding:
  name: prowler-read-cluster-binding
configMap:
  name: prowler-hostpaths
configMapData:
  varLibCni: "/var/lib/cni"
  varLibEtcd: "/var/lib/etcd"
  varLibKubelet: "/var/lib/kubelet"
  varLibKubeScheduler: "/var/lib/kube-scheduler"
  varLibKubeControllerManager: "/var/lib/kube-controller-manager"
  etcSystemd: "/etc/systemd"
  libSystemd: "/lib/systemd"
  srvKubernetes: "/srv/kubernetes"
  etcKubernetes: "/etc/kubernetes"
  usrBin: "/usr/bin"
  etcCniNetd: "/etc/cni/net.d"
  optCniBin: "/opt/cni/bin"
