apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  varLibCni: "/var/lib/cni"
  varLibEtcd: "/var/lib/etcd"
  varLibKubelet: "/var/lib/kubelet"
  varLibKubeScheduler: "/var/lib/kube-scheduler"
  varLibKubeControllerManager: "/var/lib/kube-controller-manager"
  etcSystemd: "/etc/systemd"
  libSystemd: "/lib/systemd"
  etcKubernetes: "/etc/kubernetes"
  usrBin: "/usr/bin"
  etcCniNetd: "/etc/cni/net.d"
  optCniBin: "/opt/cni/bin"

